version: "3"

services:
    redis:
        image: redis
        hostname: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            gateway:
                aliases:
                    - redis
    
    mongo:
        image: mongo:3
        container_name: mongo
        command: mongod --smallfiles --bind_ip_all
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        networks:
            - gateway

    gateway:
        build: .
        container_name: gateway
        ports:
            - "8080:8080"
            - "80:80"
            - "8443:8443"
            - "9876:9876"
        volumes:
            - ./config/system.config.yml:/usr/src/app/config/system.config.yml
            - ./config/gateway.config.yml:/usr/src/app/config/gateway.config.yml
        networks:
            - gateway

    connection:
        image: shipyardsuite/connection:develop
        command: sh -c 'npm run start:dev'
        container_name: connection
        ports:
            - "3069:3069"
        networks:
            - gateway
        environment:
            SERVICE_NAME: connection
            SERVICE_PORT: 3069
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_CONNECTION} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    homepage:
        image: shipyardsuite/homepage:develop
        command: sh -c 'npm run start:dev'
        container_name: homepage
        ports:
            - "3001:3001"
        networks:
            - gateway
        environment:
            SERVICE_NAME: homepage
            SERVICE_PORT: 3001
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_HOMEPAGE} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    auth:
        image: shipyardsuite/auth:develop
        command: sh -c 'npm run start:dev'
        container_name: auth
        ports:
            - "3002:3002"
        networks:
            - gateway
        environment:
            SERVICE_NAME: auth
            SERVICE_PORT: 3002
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_AUTH} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    documentation:
        image: shipyardsuite/documentation:develop
        command: sh -c 'npm run start:dev'
        container_name: documentation
        ports:
            - "3003:3003"
        networks:
            - gateway
        environment:
            SERVICE_NAME: documentation
            SERVICE_PORT: 3003
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_DOCUMENTATION} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    dashboard:
        image: shipyardsuite/dashboard:develop
        command: sh -c 'npm run start:dev'
        container_name: dashboard
        ports:
            - "3004:3004"
        networks:
            - gateway
        environment:
            SERVICE_NAME: dashboard
            SERVICE_PORT: 3004
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_DASHBOARD} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    player:
        image: shipyardsuite/player:develop
        command: sh -c 'npm run start:dev'
        container_name: player
        ports:
            - "3006:3006"
        networks:
            - gateway
        environment:
            SERVICE_NAME: player
            SERVICE_PORT: 3006
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_PLAYER} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    project:
        image: shipyardsuite/project:develop
        command: sh -c 'npm run start:dev'
        container_name: project
        ports:
            - "3007:3007"
        networks:
            - gateway
        environment:
            SERVICE_NAME: project
            SERVICE_PORT: 3007
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_PROJECT} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    status:
        image: shipyardsuite/status:develop
        command: sh -c 'npm run start:dev'
        container_name: status
        ports:
            - "3008:3008"
        networks:
            - gateway
        environment:
            SERVICE_NAME: status
            SERVICE_PORT: 3008
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_STATUS} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

    user:
        image: shipyardsuite/user:develop
        command: sh -c 'npm run start'
        container_name: user
        ports:
            - "3009:3009"
        networks:
            - gateway
        environment:
            SERVICE_NAME: user
            SERVICE_PORT: 3009
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID_USER} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3
            

networks:
    gateway:
